### ISSUE TITLE
Error: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/installer-action#160]
Wenn ich die aktuelle Installer Action (1.1) verwenden möchte, erhalte ich für das Addon MultiNewsletter folgenden Fehler:

```
Run FriendsOfREDAXO/installer-action@v1
  with:
    myredaxo-username: ***
    myredaxo-api-key: ***
    description: - Installer Action aktualisiert.
    version: 3.5.1
    cwd: .
Parsing yaml from package.yml
Fetch package.yml from redaxo.org for addon multinewsletter
Using login: ***
Error: TypeError: Cannot convert undefined or null to object
/home/runner/work/_actions/FriendsOfREDAXO/installer-action/v1/dist/index.js:36212
    return Object.values(packageYml.files).some(file => file.version === version);
                  ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at versionExists (/home/runner/work/_actions/FriendsOfREDAXO/installer-action/v1/dist/index.js:36212:19)
    at /home/runner/work/_actions/FriendsOfREDAXO/installer-action/v1/dist/index.js:36104:42
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

In Version 1.0.6 hat noch alles funktioniert.

**Comment by alxndr-w** [comment]
https://github.com/FriendsOfREDAXO/redactor/actions/runs/7330756667/job/19962357727#step:5:21

dito

**Comment by alxndr-w** [comment]
@TobiasKrais ist das Problem für dich noch aktuell? Bei mir nicht. Falls doch, mach einfach wieder auf.
